apiVersion: apps/v1
kind: Deployment
metadata:
 name: pet-shop-crud
spec:
 replicas: 2
 selector:
    matchLabels:
      app: pet-shop-crud
 template:
   metadata:
    labels:
     app: pet-shop-crud
   spec:
     containers:
       - name: pet-shop-crud
         image: breno500as/pet-shop-crud:v4
         ports:
          - name: http
            containerPort: 8081
         livenessProbe:
           httpGet: 
            path: /crud/actuator/health/liveness
            port: http
           periodSeconds: 100
           initialDelaySeconds: 100
           timeoutSeconds: 10
         readinessProbe:
           httpGet:
             path: /crud/actuator/health/readiness
             port: http
           periodSeconds: 100
           initialDelaySeconds: 100
           timeoutSeconds: 10