apiVersion: apps/v1
kind: Deployment
metadata:
 name: pet-shop-finances
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-shop-finances
  template:
    metadata:
     labels:
      app: pet-shop-finances
    spec:
      containers:
       - name: pet-shop-finances
         image: breno500as/pet-shop-finances:v2
         ports:
          - name: http
            containerPort: 8082
         livenessProbe:
            httpGet:
             path: /financa/actuator/health/liveness
             port: http
            timeoutSeconds: 100
            initialDelaySeconds: 100
            periodSeconds: 10         
         readinessProbe:
            httpGet:
              path: /financa/actuator/health/readiness
              port: http
            timeoutSeconds: 100
            initialDelaySeconds: 100
            periodSeconds: 10
         resources: #requisição de 10% da cpu
          requests:
            cpu: 200m
---

#Escalabilidade horizontal automática
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pet-shop-finances-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pet-shop-finances
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 6
          
#Testando a escalabilidade horizontal fazendo um loop infinito no servidor
#while true; do wget -q -O- --header "Authorization: Bearer eyJraWQiOiJwZXQtc2hvcC1zZWN1cml0eUBpc3Rpby1wZXQtc2hvcC1zZWN1cml0eS5oZXJva3VhcHAuY29tIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJwZXQtc2hvcC1zZWN1cml0eUBpc3Rpby1wZXQtc2hvcC1zZWN1cml0eS5oZXJva3VhcHAuY29tIiwiaXNzIjoicGV0LXNob3Atc2VjdXJpdHlAaXN0aW8tcGV0LXNob3Atc2VjdXJpdHkuaGVyb2t1YXBwLmNvbSIsImV4cCI6MTYwMjM5MzE0MywibG9naW4iOiJicmVubyIsImlhdCI6MTYwMjM4OTU0M30.comdsd8UxUQd5aRBKbOETN0xwK_yeOgugt5_BcKYqqZoQRWQa9mZyZrKpcjH3J-tGDCYkpnrHzoWYJGsyPRC3BNT3i1ZnSt6eRwOgccyEFH_RohmRjjlCVQFfivcPuJ0JSXznNH2__ggOv1byVj6p4dO0r93pN4p2xF-_5Qnr1G09yVyP-UmqTwjg6QrFIGdfK4fUQXFyfDUxA0H8nCjsFd40qWf0SgvIfNSDrG32vln-MRwdhuyYfNyyBnrj74-wkXfKoU5CAp6cxNYhDoikwZhMTZ7lS_nJ6PHpZuKy1NFniTWffPrB4RcLBlzDYEBYGFhI6nftu9ZLlR62RQv_A" http://172.17.0.2:30485/financa/cartoes; done
   
   
   
   