apiVersion: v1
kind: Service
metadata:
 name: pet-shop-finances-service
spec:
  selector:
   app: pet-shop-finances
  type: NodePort
  ports:
   - name: http #nome da porta para acessar o container docker dentro do pod, é o mesmo nome configurado no objeto deployment
     port: 80 #porta externa de acesso ao serviço
     targetPort: 8082 #porta para acessar o container docker dentro do pod
